#!/usr/bin/env bash

# THEME='Manhattan'
# ICONS='Luv-Folders-Dark'
# FONT='Noto Sans 9'
# CURSOR='Qogirr-Dark'
THEME='Catppuccin-Macchiato-Standard-Teal-Dark'
ICONS='WhiteSur-dark'
# FONT='Noto Sans 10'
CURSOR='Qogir-dark'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
# 	${SCHEMA} font-name "$FONT"
}

apply_themes
