#!/bin/bash

# this script will echo the playing media artist title and artUrl

# get the current playing media
if [[ $(playerctl status) != "Playing" ]]; then
  echo "No media playing"
  exit 0
fi
artist=$(playerctl metadata xesam:artist)
title=$(playerctl metadata xesam:title)

tooltip="$artist - $title"

echo "$tooltip"
