#!/usr/bin/env bash
sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &


# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Start gnome keyring
exec gnome-keyring-daemon --daemonize --start --components=gpg,pkcs11,secrets,ssh &

exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec greenclip daemon &
# Set wallpaper
swaybg --output 'eDP-1' --mode fill --image /home/xaprier/Pictures/wallpaper/davina1.jpg &
swaybg --output 'HDMI-A-1' --mode fill --image /home/xaprier/Pictures/wallpaper/davina3.jpg &
#mpvpaper HDMI-A-1 ~/Pictures/wallpaper/mylivewallpapers-com-Astronaut-Portal-FHD.mp4
#mpvpaper eDP-1 ~/Pictures/wallpaper/mylivewallpapers-com-Drifting-Spaceman.mp4
# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# virtual mic
~/.config/hypr/scripts/virtual_mic &

# Start network manager applet
nm-applet --indicator &

# Start mpd
exec mpd &

notify-send "Hyprland" "Launched" &
