#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
# Script to control prefered apps to launch for all themes
# Author: z0mbi3
# url:    https://github.com/gh0stzk

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
--menu)
    rofi -show drun -theme "$HOME"/.config/bspwm/scripts/Launcher.rasi
    ;;
--rice)
    RiceSelector
    ;;
--code)
    code
    ;;
--terminal)
    Term --terminal
    ;;
--floating)
    Term --floating
    ;;
--update)
    Term --update
    ;;
--checkupdates)
    Term --checkupdates
    ;;
--netmanager)
    NetManagerDM
    ;;
--ranger)
    Term --ranger
    ;;
--nvim)
    Term --nvim
    ;;
--music)
    Term --music
    ;;
--top)
    Term --top
    ;;
--fetch)
    Term --fetch
    ;;
    # Apps
--filemanager)
    thunar
    ;;
--browser)
    flatpak run io.github.zen_browser.zen
    ;;
--editor)
    xed
    ;;
--telegram)
    telegram-desktop
    ;;
--whats)
    whatsdesk --disable-gpu
    ;;
--soundcontrol)
    pavucontrol
    ;;
--screenshot)
    flameshot gui
    ;;
    # Eww Widgets
--KeyHelp)
    eww -c "$WIDGET_DIR" open --toggle csheet
    ;;
--powermenu)
    eww -c "$WIDGET_DIR" open --toggle powermenu
    ;;
--usercard)
    eww -c "$WIDGET_DIR" open --toggle launchermenu
    ;;
--player)
    eww -c "$WIDGET_DIR" open --toggle music
    ;;
--calendar)
    eww -c "$WIDGET_DIR" open --toggle date
    ;;
*)
    echo "Invalid Option"
    ;;
esac
