#!/usr/bin/env bash

# Import Current Theme
bspwm_dir="$HOME/.config/bspwm"
rasi_file="$bspwm_dir/scripts/Powermenu.rasi"

# Options for powermenu
lock=""
logout=""
shutdown=""
reboot=""
sleep=""

# Get answer from user via rofi
selected_option=$(echo "$lock
$logout
$sleep
$reboot
$shutdown" | rofi -dmenu \
  -i \
  -p "Power" \
  -config "$rasi_file" \
  -font "Symbols Nerd Font 12" \
  -width "15" \
  -lines 5 \
  -line-margin 3 \
  -line-padding 10 \
  -scrollbar-width "0")

# Do something based on selected option
if [ "$selected_option" == "$lock" ]; then
  betterlockscreen -l
elif [ "$selected_option" == "$logout" ]; then
  if pgrep i3; then
    i3-msg exit
  elif pgrep Hyprland; then
    hyprctl dispatch exit
  elif pgrep bspwm; then
    bspc quit
  fi
elif [ "$selected_option" == "$shutdown" ]; then
  systemctl poweroff
elif [ "$selected_option" == "$reboot" ]; then
  systemctl reboot
elif [ "$selected_option" == "$sleep" ]; then
  amixer set Master mute
  systemctl suspend
else
  echo "No match"
fi
