# (Onedark) Color scheme for Isabel Rice

# Default colors
[colors.primary]
background = "#14171c"
foreground = "#abb2bf"

# Cursor colors
[colors.cursor]
cursor = "#abb2bf"
text = "#14171c"

# Normal colors
[colors.normal]
black = "#1e2127"
blue = "#4889be"
cyan = "#49919a"
green = "#81ae5f"
magenta = "#7560d3"
red = "#be5046"
white = "#abb2bf"
yellow = "#d19a66"

# Bright colors
[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#8677cf"
red = "#e06c75"
white = "#ffffff"
yellow = "#e5c07b"
